server:
  port: 5050
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hackatom
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update